server:
  port: 8682
spring:
  application:
    name: "gateway-service"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes[0]:
        id: "business"
        uri: "lb://business"
        predicates[0]: "Path=/user/**"


    consul:
      host: localhost
      port: 8500
      config:
        enabled: false

