server:
  port : 8081
spring:
  profiles:
    active: local
  application:
    name: "business"
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        register: true
        instanceId: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        prefer-ip-address: true
        health-check-critical-timeout: "1m"
      config:
        enabled: false